CREATE TABLE PLANETAS
(
  planetaID VARCHAR(15) NOT NULL PRIMARY KEY,
  estacion VARCHAR(255) NOT NULL,
  distanciaSol INT CHECK (distanciaSol > 0 AND distanciaSol < 1000000),
  gravedad INT NOT NULL,
  poblacion INT NOT NULL
);

CREATE TABLE RUTAS
(
  rutaID VARCHAR(5) NOT NULL PRIMARY KEY,
  origen VARCHAR(15) NOT NULL,
  destino VARCHAR(15) NOT NULL,
  distancia INT NOT NULL,
  duracion INT NOT NULL,
  FOREIGN KEY (origen) REFERENCES PLANETAS(planetaID),
  FOREIGN KEY (destino) REFERENCES PLANETAS(planetaID)
);


CREATE TABLE NAVES
(
  naveID VARCHAR(15) NOT NULL PRIMARY KEY,
  modelo VARCHAR(255) NOT NULL,
  capacidad INT CHECK (capacidad > 0 AND capacidad < 300),
  velocidadMax INT NOT NULL,
  rutaID VARCHAR(5) NOT NULL,
  FOREIGN KEY (rutaID) REFERENCES RUTAS(rutaID)
);

CREATE TABLE CHOFERES
(
  choferID VARCHAR(25) NOT NULL PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  edad INT NOT NULL,
  genero CHAR(1) NOT NULL,
  nacionalidad VARCHAR(255) NOT NULL,
  naveID VARCHAR(15) NOT NULL,
  FOREIGN KEY (naveID) REFERENCES NAVES(naveID)
);

CREATE TABLE PASAJEROS
(
  pasajeroID VARCHAR(30) NOT NULL PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  apellido VARCHAR(255) NOT NULL,
  edad INT NOT NULL,
  genero CHAR(1) NOT NULL,
  nacionalidad VARCHAR(255) NOT NULL,
  naveID VARCHAR(15) NOT NULL,
  FOREIGN KEY (naveID) REFERENCES NAVES(naveID)
);